#ifndef SYSCALLLIST
#define SYSCALLLIST

#include<bits/stdc++.h>
using namespace std;

vector<string> SANDBOX_SYSTEMCALLS = { "acct",
        "add_key",
        "bpf",
        "chown",
        "clock_adjtime",
        "clock_settime",
        "create_module",
        "delete_module",
        "fchown",
        "fchownat",
        "finit_module",
        "get_kernel_syms",
        "get_mempolicy",
        "init_module",
        "ioperm",
        "iopl",
        "kcmp",
        "kexec_file_load",
        "kexec_load",
        "keyctl",
        "lchown",
        "lookup_dcookie",
        "mbind",
        "mount",
        "move_pages",
        "name_to_handle_at",
        "nfsservctl",
        "open_by_handle_at",
        "perf_event_open",
        "personality",
        "pivot_root",
        "process_vm_readv",
        "process_vm_writev",
        "ptrace",
        "query_module",
        "quotactl",
        "reboot",
        "request_key",
        "set_mempolicy",
        "setgid",
        "setns",
        "setregid",
        "setreuid",
        "settimeofday",
        "setuid",
        "stime",
        "swapon",
        "swapoff",
        "_sysctl",
        "umount",
        "umount2",
        "unshare",
        "uselib",
        "userfaultfd",
        "vm86",
        "vm86old",
    };

#endif // SECCOMPUTILS_H
